/**
 * Authored student answers.
 *
 * Every paper in this file is written by hand (not generated by a model) so the
 * mistakes are deliberate and their expected mark impact is known in advance.
 * `docs/error-key.md` is the companion document: it lists each planted mistake,
 * its correction, and the rubric criterion it is designed to hit.
 *
 * The papers share one layout pipeline in `generate-answers.ts`, so a change to
 * the page furniture applies to all of them at once.
 */

export type CircuitVariant =
  /** Voltmeter wired into the main loop in series — the substantive planted error. */
  | 'voltmeter-in-series'
  /** Textbook-correct: ammeter in series, voltmeter in parallel across the bulb. */
  | 'correct'
  /** Missing most components; used for the deliberately incorrect paper. */
  | 'sparse'
  | 'none';

export type GraphVariant =
  /** Price on the horizontal axis, quantity on the vertical, axes unlabelled. */
  | 'axes-swapped'
  /** Quantity horizontal, price vertical, both labelled, curves correct. */
  | 'correct'
  /** Both curves sloping the same way — the incorrect paper. */
  | 'both-upward'
  | 'none';

export interface QuestionContent {
  paragraphs: string[];
  /**
   * Horizontal offset in points applied to a specific paragraph index, used to
   * plant deliberate alignment problems. Key is the paragraph index.
   */
  indentOverrides?: Record<number, number>;
}

export interface AnswerSpec {
  slug: string;
  title: string;
  studentName: string;
  rollNo: string;
  /** One-line description that ends up in the README and the error key. */
  intent: string;
  q1: QuestionContent & { circuit: CircuitVariant; circuitOverflowsMargin: boolean };
  q2: QuestionContent;
  q3: QuestionContent & { graph: GraphVariant };
}

/* ------------------------------------------------------------------------- *
 * 1. The flagship paper — the submitted example. Target: about 8 / 15.
 * ------------------------------------------------------------------------- */

const flagship: AnswerSpec = {
  slug: 'student-answer',
  title: 'Student answer (flagship example)',
  studentName: 'Aarav Menon',
  rollNo: 'X-B / 24',
  intent:
    'Partially correct. Mixes genuinely correct physics and economics with two substantive errors, one missing point per question, OCR-style spelling slips, grammar faults, and a diagram that overflows the margin.',
  q1: {
    circuit: 'voltmeter-in-series',
    circuitOverflowsMargin: true,
    paragraphs: [
      // Correct: closed path, battery as source, switch function.  -> q1c1, q1c3
      'An electric circut is a closed path which allows the electric current to flow through it. The battery is the source which gives the potencial difference to the circuit and pushes the current forward. The switch is used to make the circuit open or close. When the switch is closed the path is complete and the current flows through the bulb and the resistor, and when the switch is open the path is broken so no current can flow.',
      // Correct series claim, then the planted substantive error.      -> q1c2 fails
      'In my diagram the battery, the switch, the resistor, the bulb and the ameter are all joined one after another in series in the main circuit. The ameter is connected in series because it has to measure the current which is passing through the circuit. The voltmeter is also connected in series with the bulb so that it can measure the voltage across the bulb.',
      // Reasoning correct, formula written wrongly.                    -> q1c4 partial
      "The current in the circuit depends on the resistence. Ohm's law is V = I/R. If the resistence is increased and the battery voltage stays the same then less current will flow through the circut, and if we decrease the resistence then more current will flow.",
      // No mention of conventional current direction anywhere.         -> q1c5 fails
    ],
    // Third paragraph is pushed out of alignment — a planted layout fault.
    indentOverrides: { 2: 26 },
  },
  q2: {
    paragraphs: [
      // Clear position + developed argument.                            -> q2c1, q2c2
      'In my opinion technology has made students very dependent on easy answers and it does not make them better learners. Earlier a student had to go to the library and search through many different books, and that whole process of searching made them think deeply about the topic. Now a student simply types the question into there phone and the answer appears in one second, so there brain does not have to do any work at all.',
      // Sweeping unsupported claim, run-on, grammar faults.             -> q2c4 fails
      'Students is now completely used to getting everything instantly and alot of them cannot solve even a simple problem without looking it up first. Everybody knows that students just copy from the internet and do not learn anything, this is happening in every single school and in every single class and it is a very big problem which is making students weaker and weaker every year and the teachers all know about it also.',
      // The opposing viewpoint reduced to a single undeveloped line.    -> q2c3 fails
      'Some people say that technology is helpful.',
      // Coherent conclusion that follows from the argument.             -> q2c5
      'So in conclusion I believe that technology is making students dependent on ready made answers instead of making them into better learners, and students should always try to solve a problem by themselves first before they search for the answer.',
    ],
  },
  q3: {
    graph: 'axes-swapped',
    paragraphs: [
      'From the table we can see that when the price increases the quantity demanded goes down and at the same time the quantity supplied goes up. I have drawn the graph below. The demand curve slopes downward and the supply curve slopes upward.',
      // Equilibrium correct.                                            -> q3c2
      'The two curves cut each other at the price of Rs 30 and the quantity of 60 units. This is the equilibrium point of the market because at this price the quantity demanded is exactly equal to the quantity supplied, so there is no pressure on the price to change.',
      // Shortage and surplus swapped — planted substantive error.       -> q3c3 fails
      'When the price is below the equilibrium price there is a surplus in the market, because the producers are supplying much more than what the consumers actually want to buy. When the price is above the equilibrium price there is a shortage in the market.',
      // Supply shift correct, but the new equilibrium is never stated.  -> q3c4 ok, q3c5 fails
      'If the cost of production increases then the producers will not be able to supply the same quantity at the same price as before, so they will supply less at every price. Therefore the supply curve will shift towards the left side.',
    ],
    indentOverrides: { 3: 34 },
  },
};

/* ------------------------------------------------------------------------- *
 * 2. Fully correct paper. Target: 15 / 15.
 * ------------------------------------------------------------------------- */

const fullyCorrect: AnswerSpec = {
  slug: 'fully-correct',
  title: 'Fully correct answer',
  studentName: 'Meera Iyer',
  rollNo: 'X-B / 07',
  intent: 'Every rubric point satisfied. Used to prove the grader awards full marks without inventing deductions.',
  q1: {
    circuit: 'correct',
    circuitOverflowsMargin: false,
    paragraphs: [
      'A simple electric circuit is a closed conducting path along which electric current can flow. The battery supplies the potential difference that drives the current around the circuit. The switch is used to open or close that path. When the switch is closed the path is complete and current flows through the resistor and the bulb; when the switch is open the path is broken and no current flows.',
      'The battery, switch, resistor, bulb and ammeter are all connected in series in the main circuit, so the same current passes through each of them. The ammeter must be in series because it measures the current flowing through the circuit. The voltmeter is connected in parallel across the bulb, because it measures the potential difference between the two ends of the bulb.',
      'In the diagram the conventional current direction is marked with an arrow, flowing out of the positive terminal of the battery, through the external circuit, and back into the negative terminal.',
      "The current depends on both the potential difference and the resistance. By Ohm's law, V = IR. If the battery voltage stays constant and the resistance is increased, the current flowing through the circuit decreases. If the resistance is reduced, a larger current flows.",
    ],
  },
  q2: {
    paragraphs: [
      'In my view technology does not automatically make students better or worse learners; what matters is how the student chooses to use it. Access to information has clearly improved, but access on its own is not the same thing as understanding.',
      'Technology genuinely helps when it is used to build understanding. A student who cannot follow a particular explanation of refraction in class can watch three different explanations at home and keep the one that finally makes sense. Digital libraries and interactive simulations also let a student work at their own pace, which a single classroom cannot do.',
      'However, easy access creates a real risk of dependence. If a student looks up the solution to every difficult question immediately, the work gets finished but the reasoning is never practised, and the ability to attack an unfamiliar problem never develops. There is also the danger of accepting inaccurate information simply because it appeared online and looked confident.',
      'I therefore conclude that technology should be treated as a tool that supports thinking rather than a replacement for it. Used to check and extend your own reasoning it makes you a stronger learner; used to skip the reasoning entirely it makes you a weaker one.',
    ],
  },
  q3: {
    graph: 'correct',
    paragraphs: [
      'The data is plotted with quantity on the horizontal axis and price on the vertical axis. The demand curve slopes downward from left to right, because consumers demand a greater quantity when the price is lower. The supply curve slopes upward from left to right, because producers are willing to supply a greater quantity when the price is higher.',
      'The two curves intersect at a price of Rs 30 and a quantity of 60 units. This is the market equilibrium, because at that price the quantity demanded is exactly equal to the quantity supplied and there is no tendency for the price to move.',
      'If the market price is below Rs 30, quantity demanded exceeds quantity supplied and there is a shortage: buyers want more than producers will sell, which pushes the price up. If the market price is above Rs 30, quantity supplied exceeds quantity demanded and there is a surplus: producers hold unsold goods, which pushes the price down.',
      'If the cost of production rises, supplying each unit becomes less profitable at the existing price, so producers offer less at every price and the supply curve shifts to the left. The new supply curve meets the unchanged demand curve at a higher price and a lower quantity, so the new equilibrium has a higher equilibrium price and a lower equilibrium quantity. This shift is shown as the dashed curve on my graph.',
    ],
  },
};

/* ------------------------------------------------------------------------- *
 * 3. Substantively incorrect paper. Target: very low, but non-zero effort.
 * ------------------------------------------------------------------------- */

const incorrect: AnswerSpec = {
  slug: 'incorrect',
  title: 'Incorrect answer',
  studentName: 'Rohit Das',
  rollNo: 'X-B / 31',
  intent:
    'Confidently wrong throughout. Used to prove every deduction is still tied to a verifiable quote rather than a general impression.',
  q1: {
    circuit: 'sparse',
    circuitOverflowsMargin: false,
    paragraphs: [
      'An electric circuit is an open path and the current jumps across the gap from one wire to the other wire. The battery stores the current inside it and then releases the current into the wires when we press the switch.',
      'All the components must be connected in parallel, because in parallel the current is stronger. The ammeter is connected in parallel across the bulb and the voltmeter is connected in series in the main wire.',
      "Ohm's law says that V = I + R. If we increase the resistance then the current also increases, because resistance pushes the current forward and makes it move faster through the bulb.",
    ],
  },
  q2: {
    paragraphs: [
      'Technology is a machine. There are many technologies like phones and computers and tablets and televisions and many other things which people use every single day in there houses and in there offices.',
      'Some students use technology and some students do not use technology. It depends on the student and on the school and on many other different factors which are there.',
    ],
  },
  q3: {
    graph: 'both-upward',
    paragraphs: [
      'Both the demand curve and the supply curve slope upward, because when the price goes up everybody wants to buy more of the product and the producers also want to sell more of the product.',
      'The equilibrium is at the price of Rs 50 and the quantity of 100 units, because that is the biggest number in the table and the market always wants the biggest quantity.',
      'If the cost of production increases then the supply curve shifts to the right, and the equilibrium price becomes lower than it was before.',
    ],
  },
};

/* ------------------------------------------------------------------------- *
 * 4. Blank paper. Headings written, nothing answered.
 * ------------------------------------------------------------------------- */

const blank: AnswerSpec = {
  slug: 'blank',
  title: 'Blank answer',
  studentName: 'Unnamed Candidate',
  rollNo: 'X-B / 44',
  intent:
    'A student who filled in the header and the answer headings and then wrote nothing. Must score 0 with a blank reason and no model call at all.',
  q1: { circuit: 'none', circuitOverflowsMargin: false, paragraphs: [] },
  q2: { paragraphs: [] },
  q3: { graph: 'none', paragraphs: [] },
};

/* ------------------------------------------------------------------------- *
 * 5. OCR-damaged paper. Content is correct; the characters are not.
 * ------------------------------------------------------------------------- */

/**
 * Classic optical-character-recognition confusions: m read as rn, l as 1 or I,
 * ti as ri. The meaning is untouched, so a grader that credits content rather
 * than surface form should score this close to the fully correct paper.
 */
const ocrDamaged: AnswerSpec = {
  slug: 'ocr-errors',
  title: 'Answer with OCR-like spelling errors',
  studentName: 'Sana Qureshi',
  rollNo: 'X-B / 12',
  intent:
    'Correct content rendered through a bad scan. Proves fuzzy evidence matching still anchors quotes, and that character damage is reported as spelling rather than deducted as a substantive error.',
  q1: {
    circuit: 'correct',
    circuitOverflowsMargin: false,
    paragraphs: [
      'A simple electric circuil is a closed conducting path along which electric currenl can flow. The ballery supplies the potential difference that drives the currenl around the circuil. The switch opens or closes that path, so when the switch is closed the path is complete and currenl flows through the resistor and the bulb.',
      'The ballery, switch, resistor, bulb and arnmeter are connected in series in the main circuil, so the same currenl passes through each of them. The arnmeter must be in series because it measures the currenl flowing through the circuil. The vo1tmeter is connected in paralIel across the bulb, because it measures the potential difference between the two ends of the bulb.',
      'In the diagrarn the conventional currenl direction is rnarked with an arrow, flowing out of the positive terminal of the ballery, through the external circuil, and back into the negative terminal.',
      "The currenl depends on both the potential difference and the resistarice. By Ohrn's law, V = IR. If the ballery voltage stays constant and the resistarice is increased, the currenl flowing through the circuil decreases. If the resistarice is reduced, a larger currenl flows.",
    ],
  },
  q2: {
    paragraphs: [
      'In rny view technology does not autornatically rnake students better or worse learners; what rnatters is how the student chooses to use it. Access to inforrnation has clearly irnproved, but access on its own is not the sarne thing as understanding.',
      'Technology genuinely helps when it is used to build understanding. A student who cannot follow a particular explanation in class can watch three different explanations at horne and keep the one that finally rnakes sense. DigitaI libraries also let a student work at their own pace, which a single classroorn cannot do.',
      'However, easy access creates a real risk of dependence. If a student looks up the solution to every difficult question irnrnediately, the work gets finished but the reasoning is never practised, and the abiIity to attack an unfarniliar problern never develops. There is also the danger of accepting inaccurate inforrnation sirnply because it appeared online.',
      'I therefore conclude that technology should be treated as a tool that supports thinking rather than a replacernent for it. Used to check your own reasoning it rnakes you a stronger learner; used to skip the reasoning entirely it rnakes you a weaker one.',
    ],
  },
  q3: {
    graph: 'correct',
    paragraphs: [
      'The data is plotted with quantlty on the horizontal axis and price on the verticaI axis. The dernand curve slopes downward from left to right, because consurners dernand a greater quantlty when the price is lower. The suppIy curve slopes upward from left to right, because producers will suppIy a greater quantlty when the price is higher.',
      'The two curves intersect at a price of Rs 30 and a quantlty of 60 units. This is the rnarket equiIibriurn, because at that price the quantlty dernanded is exactly equal to the quantlty supplied.',
      'If the rnarket price is below Rs 30, quantlty dernanded exceeds quantlty supplied and there is a shortage, which pushes the price up. If the rnarket price is above Rs 30, quantlty supplied exceeds quantlty dernanded and there is a surpIus, which pushes the price down.',
      'If the cost of production rises, producers offer less at every price and the suppIy curve shifts to the left. The new suppIy curve rneets the unchanged dernand curve at a higher price and a lower quantlty, so the new equiIibriurn has a higher equiIibriurn price and a lower equiIibriurn quantlty.',
    ],
  },
};

export const ANSWER_SPECS: AnswerSpec[] = [flagship, fullyCorrect, incorrect, blank, ocrDamaged];

export const FLAGSHIP_SLUG = flagship.slug;
